import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Chivo } from "next/font/google";
import { Container } from "@mui/material";

const chivo = Chivo({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={chivo.className}>
      <body>
        <Container
          maxWidth={false}
          sx={{
            display: "flex",
            flexDirection: "column",
            gap: "30px",
            paddingLeft: "0px",
            paddingRight: "0px",
          }}
        >
          {children}
        </Container>
      </body>
    </html>
  );
}
