import type { Metadata } from "next";
import { Chivo } from "next/font/google";
import { Container } from "@mui/material";

const chivo = Chivo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container
      maxWidth={"lg"}
      sx={{ display: "flex", flexDirection: "column", gap: "30px" }}
      className={chivo.className}
    >
      {children}
    </Container>
  );
}
